[package]
name = "rk-frontend"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "visual editor"
build = "build.rs"

[[bin]]
name = "rk"
path = "src/main.rs"

[dependencies]
rk-core = { workspace = true }
rk-cad = { workspace = true }
rk-engine = { workspace = true }
rk-renderer = { workspace = true }
egui = { workspace = true }
egui_dock = { workspace = true }
egui-wgpu = { workspace = true }
eframe = { workspace = true, features = ["x11", "wayland"] }
wgpu = { workspace = true }
glam = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ron = { workspace = true }
dirs = { workspace = true }
ureq = { workspace = true }
semver = { workspace = true }
open = { workspace = true }

[build-dependencies]
winres = { workspace = true }
